from enum import Enum


class GameStatus(Enum):
    WAITING_FOR_NEXT_PLAYER = "WAITING_FOR_NEXT_PLAYER"
    WAITING_FOR_PLAYER_TO_START = "WAITING_FOR_PLAYER_TO_START"
    RUNNING = "RUNNING"
    STOPPED = "STOPPED"
    PAUSED = "PAUSED"
    RESETTING = "RESETTING"
    GAME_OVER = "GAME_OVER"

